# Generated by Django 4.0.2 on 2022-02-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descriptio',
            new_name='description',
        ),
    ]
